# Generated by Django 2.2.6 on 2019-10-17 08:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import registration.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Name should contain only                                         characters from a-z or A-Z', regex='^[a-zA-Z][a-zA-Z\\s]*$')], verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phonenumber', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator(message='Invalid Phonenumber', regex='^(?:(?:\\+|0{0,2})91(\\s*[\\-]\\s*)?|[0]?)?[789]\\d{9}$')], verbose_name='Phone Number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('address', models.TextField(blank=True, max_length=500, null=True, verbose_name='Address')),
                ('pan', models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Invalid PAN Number', regex='^[A-Z]{5}[0-9]{4}[A-Z]{1}$')], verbose_name='PAN')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(max_length=50)),
                ('razp_id', models.CharField(blank=True, max_length=22, null=True)),
                ('txn_id', models.CharField(default=registration.models.generate_id, max_length=64)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='RazorpayTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('currency_type', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=50)),
                ('razorpay_id', models.CharField(db_index=True, max_length=22)),
                ('error_code', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.CharField(blank=True, max_length=256, null=True)),
                ('transaction_id', models.CharField(db_index=True, default=registration.models.generate_id, max_length=64, unique=True)),
                ('account_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rzptn', to='registration.Account')),
            ],
            options={
                'ordering': ('-transaction_date',),
            },
        ),
    ]
